author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test2_20200713
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iiif.archivelab.org/iiif//80369326.08156.emory.edu$1/full/full/0/default.jpg
image_size:
  page:
    height: 2288
    width: 3231
permalink: pretty
publication_info:
  date: '2020'
  editors: []
  title: Laurentii Gambarae Brixiani, Rerum sacrarum liber
show_annotation_author: true
source_info:
  title: Laurentii Gambarae Brixiani, Rerum sacrarum liber
  via_readux: true
tagline: an annotated digital edition
title: Laurentii Gambarae Brixiani, Rerum sacrarum liber
url: https://jcmundy.github.io
version: 0.7
